### ISSUE TITLE
timestamp in GelfMessageBuilder should be Long?

### ISSUE THREAD

**Issue by hepin1989** [Graylog2/gelfclient#18]
I am not sure why the timestamp have the type of Double,is it designed to ?

**Comment by joschi** [comment]
We tried to stay as close to the [GELF specification](https://www.graylog.org/resources/gelf/) as possible, which states that the `timestamp` field is the "Seconds since UNIX epoch with optional decimal places for milliseconds".

This being said, we might add a wrapper method which takes a millisecond timestamp as `long`.

**Comment by hepin1989** [comment]
then why not just using the timestamp / 1000?
I think a better way would be make it clearly that the builder take a 
timestamp(long:secondsSinceUNIXEpoch)

wdyt?

**Comment by hepin1989** [comment]
thanks @joschi I just update my code to the gelf spec.
