### ISSUE TITLE
Equals, hashcode and toString are incomplete on GelfMessage

### ISSUE THREAD

**Issue by camann9** [Graylog2/gelfclient#7]
Hi,
the toString method is missing additionalFields, fullMessage, host.
The equals and hashCode methods are missing additionalFields

**Comment by joschi** [comment]
The terse representation in `GelfMessage#toString()` is intentional as we don't think printing every single attribute (including custom attributes which may be quite numerous) makes sense. The `toString()` is mostly used in debugging output where to much noise would be counter productive.

Leaving `additionalFields` out of the `equals(Object)` and `hashCode()` implementations was also intentional so that a large number of custom attributes wouldn't slow down those methods. It's certainly a tradeoff but we found it rather unlikely that messages will have the exactly same timestamp, message, and fullMessage, but have different custom attributes.

Did you run in any specific problems because of those design decisions? If so, we'd love to hear about them in more detail!

**Comment by camann9** [comment]
Well, I wouldn't call it a "problem" :-P
I just wanted to log the generated message and the toString didn't do what I expected. I thoght it was an oversight, not a design decision.
